version: '3.7'

services:
#   grpc:
#     image: sponsianus/starlink-grpc-tools
#     command: "dish_grpc_influx.py -t 1 -a -v status obstruction_detail alert_detail ping_drop ping_run_length ping_latency ping_loaded_latency usage bulk_history"
#     tty: true
#     restart: always

  netstats:
    image: sponsianus/netstats
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always